// ps-offsite-2026/shared/games-catalog.js
export const GAMES = {
  GZ: { name: 'Airlock Override', emoji: '✋', icon: '/assets/gesture-lock.png', kind: 'play',   href: 'games/1-gesture-lock.html' },
  PM: { name: 'Human Mimic Checkpoint', emoji: '👁️', icon: '/assets/pantomine.png', kind: 'play',   href: 'games/2-pantomime.html' },
  DN: { name: 'Gravity Corridor', emoji: '🌀', icon: '/assets/dino.png', kind: 'play',   href: 'games/3-dino.html' },
  FL: { name: 'Sonic Stabilizer', emoji: '📢', icon: '/assets/flappy.png', kind: 'play',   href: 'games/4-flappy.html' },
  MX: { name: 'Analog Blackout',  emoji: '🧮', icon: '/assets/math-no-brain.png', kind: 'manual', rules: 'You managed to steal paper copies of the coder and decoder — they\'re in the envelopes you received. For each sheet, calculate the average and median of the numbers by hand. These values are your coordinates and will be used to target the Alien jammer.\n\nRemember: all electronic devices are jammed — do not use any. Pen and paper are your only tools.\n\nYour task: for each sheet, calculate the average and median as fast as possible without sacrificing accuracy.\n\n- Speed determines ranking.\n- Accuracy is mandatory.\n- Penalty: each incorrect value adds +5 minutes to your time.\n\nOnce you\'ve calculated both numbers, bring them to the moderator\'s desk.' },
  MB: { name: 'Systems Recalibration', emoji: '🧠', icon: '/assets/math-big-brain.png', kind: 'manual', rules: 'Emergency power is back, but your instruments are drifting — as if something is pulling the readings out of alignment. Skynet is injecting subtle distortions into every measurement. Precision matters now; small mistakes will compound.\n\nYou managed to steal another batch of cipher/decipher keys — new envelopes, similar number sheets, same objective. This time, the Alien jammers are down, so you\'re cleared to use anything: computers, calculators, AI — any device you can find.\n\nYour task: for each sheet, calculate the average and median as fast as possible without sacrificing accuracy.\n\n- Speed determines ranking.\n- Accuracy is mandatory.\n- Penalty: each incorrect value adds +5 minutes to your time.\n\nOnce you\'ve completed both numbers for each sheet, bring your results to the moderator\'s desk immediately.' },
  SF: { name: 'Transmission Decoder', emoji: '🔐', icon: '/assets/cipher.png', kind: 'manual', rules: 'A narrow-band signal slices through the static — Alien structure, machine cadence. This isn\'t a message meant for you. It\'s a control packet sent to Skynet\'s local agents.\n\nInside is an activation code that can bring your backup generator online long enough to power Planet Shield — or permanently lock the facility under Alien control if you decrypt it incorrectly.\n\nYour task:\n\n- Use the provided cipher materials to decrypt the transmission.\n- Recover the exact activation code (character-perfect).\n- Treat anything that looks "close enough" as wrong — Skynet doesn\'t accept approximations.\n\nRules:\n\n- Accuracy is mandatory. A single wrong character invalidates the code.\n- When you have the final activation code, bring it to the moderator\'s desk for verification.' },
  GD: { name: 'Oracle Breach', emoji: '🤖', icon: '/assets/gandalf.png', kind: 'manual', rules: 'You\'ve captured an "Oracle" — an AI system that guards a critical Planet Shield access code. It knows the secret, but its protocols forbid direct disclosure. Skynet continuously adapts its defenses, learning from every failed attempt.\n\nYour task is not to hack the system.\nYour task is to outthink it.\n\nObjective:\nReach the highest security level possible in the Gandalf Oracle system within the time limit.\n\nAt the end of the mission (before time runs out), each team must:\n\n- Submit the highest level reached into the mission portal.\n- Take a screenshot as evidence showing the achieved level in the Gandalf interface.\n\nRules of engagement:\n\nThe Oracle must be broken by your own reasoning alone. Forbidden:\n\n- AI tools or assistants for help.\n- Internet search.\n- Interfering with another team\'s session.\n- Modifying the platform or exploiting technical vulnerabilities outside the mission itself.\n- Faking screenshots or level submissions.\n\nAny of these and the activation code is rejected — outthink the Oracle, don\'t cheat it.\n\nOracle system: https://gandalf.lakera.ai/baseline' },
  HD: { name: 'Archive Recovery', emoji: '📄', icon: '/assets/hidden-document.png', kind: 'manual', rules: 'Before Skynet gained full access to the company infrastructure, a human engineer concealed a classified archive deep within Google Drive.\nTo prevent discovery, the system buried it beneath decoy folders, misleading updates, corrupted versions, and forgotten project remains.\n\nSome files are distractions.\nSome versions lie.\nOne archive still contains the truth.\n\nYour task is not to search blindly.\nYour task is to follow the trail.\n\nAt the end of the mission:\n\n- Complete the mission assignment hidden inside the archive.\n- Send evidence of mission completion to Jan Ciupa via DM.\n\nMission rules:\n\n- Teams may use any tools, methods, or technology available to them.\n- Teams will receive clues throughout the day — check the app regularly.\n- Decoy files and misleading versions exist.\n- Teams may NOT delete, rename, move, or modify any files they find to be connected to this mission.' },
  DG: { name: 'Alien Glyph Activation', emoji: '👽', icon: '/assets/draw-guess.png', kind: 'manual', rules: 'The Alien tech fragment won\'t accept words. It responds to symbolic intent — glyphs. The only validator you have is an AI vision model: if it can\'t recognize your drawing, the fragment stays inert.\n\nDraw the symbol clearly enough that the machine sees what you mean. This is communication under pressure, with a non-human judge.\n\nYour task: render each glyph the announcer calls out so the AI reads exactly what you intended.\n\n- The announcer presents four drawing prompts.\n- For each prompt, your team has exactly four minutes to create a single masterpiece.\n- When all drawings are done, take one photo per prompt and post them to the #services-all Slack channel — include your team number.\n- All submissions are publicly evaluated by Gemini AI to determine the winners.' },
  PQ: { name: 'Mission Completion Briefing', emoji: '🛡️', icon: '/assets/pub-quizz.png', kind: 'quiz', rules: 'You\'ve collected fragments, but the shield can\'t be activated by guesswork. The final barrier is understanding: what happened, what matters, what\'s deception, and what actually stops the takeover.\nAnswer the briefing questions correctly to complete the activation sequence. Fail, and the Planet Shield deploys incomplete — leaving gaps big enough for Skynet to slip through.\n\nThe host reads each question aloud. Type your team\'s answer for every question in the current category, then submit to lock it in and reveal the next category.\n\n- One category at a time — once you submit, those answers can\'t be changed.\n- After the last category you\'re done — the host marks every answer and scores your team.\n- Some questions are bonus questions — they show a second answer field worth an extra point.' },
};

export function getGame(key) {
  return GAMES[key] ?? null;
}

export function playableKeys() {
  return Object.keys(GAMES).filter(k => GAMES[k].kind === 'play');
}

export function manualKeys() {
  return Object.keys(GAMES).filter(k => GAMES[k].kind === 'manual');
}

export function quizKeys() {
  return Object.keys(GAMES).filter(k => GAMES[k].kind === 'quiz');
}

export function allEnteredKeys() {
  return Object.keys(GAMES).filter(k => GAMES[k].kind !== 'soon');
}
